
name: Node.js CI

 

on:

  push:

    branches:

      - main

 

jobs:

  build:

    name: CI

    runs-on: ubuntu-latest

 

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

      

    - name: Setup Node.js

      uses: actions/setup-node@v2

      with:

        node-version: 18

 

    - name: Install dependencies

      run: npm install

        

    - name: Display .env file

      run: |

            echo "MYSQL_DATABASE=sys" >> .env
            echo "MYSQL_USER=root" >> .env
            echo "MYSQL_PASSWORD=root" >> .env
            echo "MYSQL_PORT=3306" >> .env
            echo "MYSQL_HOST=127.0.0.1" >> .env
            echo "DB_DIALECT=mysql" >> .env

            cat .env

 

       

    - name: configuremysql

      run: |

        sudo apt-get update

        sudo apt-get install -y curl

        sudo systemctl start mysql

        sudo systemctl status mysql


        mysql -u root -p"root"

 

    - name: Run program

      run : node app.js

    - name: Run Tests

      run : npm test
